### ISSUE TITLE
issues with generating ideal conditions with python helper scripts

### ISSUE THREAD

**Issue by kbnd** [NCAR/icar#25]
I'm trying to run an ideal case to make sure ICAR is installed properly. After creating a python2.7 environment and installing pynio and pyngl, the script 'create_geo_testfiles.py' works (creates files named lo.nc and hi.nc). The gen_init_ideal.py and gen_ideal.py scripts fail due to the following error:

NameError: a global name '_nio_addvar' is not defined

It appears _nio_addvar is not present in the mygis.py module.

In order to make gen_ideal.py and gen_init_ideal.py work (until the problem described above) I had to change the dimension variables from floats to integers (nz, nx, ny, udims, vdims, and dims) because python would complain about using float values as indices.

**Comment by gutmann** [comment]
In a nutshell, you need to install the [netcdf4-python](http://unidata.github.io/netcdf4-python/) library to read and write netcdf in python.  

Sorry, the python helper scripts aren't well documented.  They are provided more because they might help, but they are not all maintained and tested.  I figure providing them in some form is more helpful than not providing them at all.  

That said, this particular error means that the netcdf4-python library is not installed.  The mygis module tries to load netcdf4-python, if that fails, it tries to load pynio.  However, the pynio library is not as well supported as the netcdf4 library (by me, not the pynio developers).  In this case, it looks like I wrote a function call to a function like the one I have implemented for the more common netcdf4 package, but I haven't actually implemented the function... I don't use pynio anymore so I don't have an easy way to test this and add the functionality (and it's not high on the priority list.)

**Comment by kbnd** [comment]
I had installed netcdf4 for my standard python library, but didn't have it installed in the python environment setup for icar (since the helper scripts are written for python2.X and I had python 3.X). Now that netcdf4 is installed in my icar python environment, the helper script worked after ensuring all indices were integers (not floats).

**Comment by gutmann** [comment]
I've transitioned to py3k too, so they will slowly be updated. I just don't use many of these myself anymore.
